{"rt_tconst": "jersey_girl", "rt_cr": "Richard Propes", "rt_pub": "TheIndependentCritic.com", "rt_fresh": 1, "rt_cr_review": "This film should have been much better than it is.", "rt_cr_review_full_url": "https://theindependentcritic.com/jersey_girl", "rt_cr_review_date": "September 12, 2020", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Debbie Lynn Elias", "rt_pub": "Behind The Lens", "rt_fresh": 1, "rt_cr_review": "The result, a heartfelt, sweet and funny love letter to fatherhood.", "rt_cr_review_full_url": "http://behindthelensonline.net/site/reviews/jersey-girl/", "rt_cr_review_date": "November 13, 2019", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kaleem Aftab", "rt_pub": "The List", "rt_fresh": 1, "rt_cr_review": "A gem that is bound to be misconstrued.", "rt_cr_review_full_url": "https://archive.list.co.uk/the-list/2004-06-10/30/", "rt_cr_review_date": "April 18, 2019", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "David Nusair", "rt_pub": "Reel Film Reviews", "rt_fresh": 1, "rt_cr_review": "Director Kevin Smith's first non-View Askewniverse effort...", "rt_cr_review_full_url": "http://reelfilm.com/ksmith.htm#jersey", "rt_cr_review_date": "June 29, 2018", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Deborah Hornblow", "rt_pub": "Hartford Courant", "rt_cr_review": "But the formulaic nature of ``Jersey Girl'' and its unabashed embrace of suds makes it awfully sweet stuff. ``Jersey Girl'' is [Kevin] Smith at his most tender but not, alas, at his most original.", "rt_cr_review_full_url": "http://articles.courant.com/2004-03-26/features/0403260276_1_george-carlin-s-bart-trinke-affleck-s-ollie-trinke-kevin-smith", "rt_cr_review_date": "January 2, 2018", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kevin Carr", "rt_pub": "Fat Guys at the Movies", "rt_fresh": 1, "rt_cr_review": "I enjoyed the movie quite a bit... Unfortunately, Smith cannot resist his old stand-bys.", "rt_cr_review_full_url": "http://www.fatguysatthemovies.com/jersey-girl-movie-review/", "rt_cr_review_date": "January 17, 2016", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Nell Minow", "rt_pub": "Common Sense Media", "rt_top": 1, "rt_cr_review": "Formulaic script and uneven tone. Disappointing.", "rt_cr_review_full_url": "http://www.commonsensemedia.org/movie-reviews/jersey-girl ", "rt_cr_review_date": "December 24, 2010", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Felix Vasquez Jr.", "rt_pub": "Cinema Crazed", "rt_cr_review": "A cloying attempt at mainstream fodder...", "rt_cr_review_full_url": "http://cinemacrazed.wordpress.com/2005/06/05/jersey-girl-2004/", "rt_cr_review_date": "April 29, 2009", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Urban Cinefile Critics", "rt_pub": "Urban Cinefile", "rt_fresh": 1, "rt_cr_review": "Jersey Girl obeys the classic conventions of romantic comedy but there are ingredients in this mix that raise it a notch above average.", "rt_cr_review_full_url": "http://www.urbancinefile.com.au/home/view.asp?a=9242&s=Reviews", "rt_cr_review_date": "October 18, 2008", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Joe Leydon", "rt_pub": "Variety", "rt_top": 1, "rt_cr_review": "The script stoops to cheap gags that undercut Affleck's efforts to sustain a believable character.", "rt_cr_review_date": "June 23, 2008", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Neil Smith", "rt_pub": "Film4", "rt_cr_review": "Jersey Girl marks a low point for the tubby New Jersey auteur.", "rt_cr_review_full_url": "http://www.channel4.com/film/reviews/film.jsp?id=131643", "rt_cr_review_date": "June 23, 2008", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rob Gonsalves", "rt_pub": "eFilmCritic.com", "rt_fresh": 1, "rt_cr_review": "Mature and heartfelt, though not overly saccharine.", "rt_cr_review_full_url": "http://efilmcritic.com/review.php?movie=8912&reviewer=416", "rt_cr_review_date": "September 24, 2007", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Eric Melin", "rt_pub": "Lawrence.com", "rt_cr_review": "It takes more than a couple of dirty one-liners to retain your edge in light, predictable fare.", "rt_cr_review_full_url": "http://www.lawrence.com/news/2004/mar/30/review_jersey/", "rt_cr_review_date": "September 29, 2006", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Peter T. Chattaway", "rt_pub": "Christianity Today", "rt_fresh": 1, "rt_cr_review": "Affleck is at ease in this down-to-earth drama in a way that he never seems to be in his action movies, and Castro seems like a genuine child instead of like a child actor.", "rt_cr_review_date": "September 25, 2006", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Don R. Lewis", "rt_pub": "Film Threat", "rt_fresh": 1, "rt_cr_review": "Smith reinvents the romantic-comedy by making a film about a man in love with his kid.", "rt_cr_review_date": "July 22, 2006", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Mark Bourne", "rt_pub": "DVDJournal.com", "rt_fresh": 1, "rt_cr_review": "In several ways Jersey Girl is more appealing than Clerks or Mallrats.... Nonetheless, it lacks the smart observational-humor edge and often thoughtful boldness -- and, most frustratingly, the promise -- of Chasing Amy or Dogma.", "rt_cr_review_full_url": "http://www.dvdjournal.com/reviews/j/jerseygirl04.shtml", "rt_cr_review_date": "April 5, 2006", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Robert Roten", "rt_pub": "Laramie Movie Scope", "rt_cr_review": "A romantic comedy seriously marred by a clunky plot and a couple of characters that are hard to sympathize with.", "rt_cr_review_full_url": "http://www.lariat.org/AtTheMovies/dvd/jerseygirl.html", "rt_cr_review_date": "July 20, 2005", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Bill Clark", "rt_pub": "FromTheBalcony", "rt_fresh": 1, "rt_cr_review": "Jersey Girl emerges as Kevin Smith's most polished effort to date, but not his funniest.", "rt_cr_review_full_url": "http://fromthebalcony.com/movie-reviews/jersey-girl-2004/", "rt_cr_review_date": "June 20, 2005", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Garth Franklin", "rt_pub": "Dark Horizons", "rt_cr_review": "People who find Smith's work too brazen or fringe will really fall for this picture, likewise those easily pleased by this genre will enjoy. Hardcore fans may be very upset by Smith doing something so ordinary and even mundane.", "rt_cr_review_full_url": "http://www.darkhorizons.com/reviews/438/jersey-girl", "rt_cr_review_date": "April 2, 2005", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Ethan Alter", "rt_pub": "NYC Film Critic", "rt_fresh": 1, "rt_cr_review": "In a strange way, it's both the most mainstream and the most personal movie Smith has made to date.", "rt_cr_review_full_url": "http://www.nycfilmcritic.com/display_film.php?id=91", "rt_cr_review_date": "March 5, 2005", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "la_defensa_del_dragon", "rt_cr": "Tom Bond", "rt_pub": "One Room With A View", "rt_cr_review": "It's a pleasant, simple drama featuring some entertaining characters. That's about it.", "rt_cr_review_full_url": "https://oneroomwithaview.com/2017/05/28/dragons-defense-cannes-2017-review/", "rt_cr_review_date": "March 4, 2019", "url": "https://www.rottentomatoes.com/m/la_defensa_del_dragon/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "la_defensa_del_dragon", "rt_cr": "Sebastian Zavala Kahn", "rt_pub": "Cinencuentro", "rt_fresh": 1, "rt_cr_review": "A correct film that works thanks to comical touches, many lines of dialogue are funny because of the dryness in which they are said. [Full review in Spanish]", "rt_cr_review_full_url": "http://www.cinencuentro.com/2017/08/03/festival-de-lima-2017-la-defensa-del-dragon-colombia/", "rt_cr_review_date": "August 9, 2017", "url": "https://www.rottentomatoes.com/m/la_defensa_del_dragon/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "la_defensa_del_dragon", "rt_cr": "Jay Weissberg", "rt_pub": "Variety", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Static camerawork elides with static lives in Natalia Santa's rigorously controlled, fitfully amusing debut \"The Dragon Defense.\"", "rt_cr_review_full_url": "http://variety.com/2017/film/reviews/fthe-dragon-defense-review-1202477952/", "rt_cr_review_date": "July 2, 2017", "url": "https://www.rottentomatoes.com/m/la_defensa_del_dragon/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "la_defensa_del_dragon", "rt_cr": "Juanma Ruiz", "rt_pub": "Caim\u00e1n Cuadernos de Cine", "rt_fresh": 1, "rt_cr_review": "A solid story around a protagonist unable to take the reins of his own life. [Full review in Spanish]", "rt_cr_review_full_url": "https://www.caimanediciones.es/cannes-2017-en-tiempo-real-la-opinion-de-la-critica/", "rt_cr_review_date": "May 31, 2017", "url": "https://www.rottentomatoes.com/m/la_defensa_del_dragon/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "Ryan Murphy", "rt_pub": "Miami Herald", "rt_top": 1, "rt_cr_review": "Unless you're a constipated horse or a lover of truly tasteless cinema, A Fine Mess is one you don't want to wander into.", "rt_cr_review_full_url": "https://www.newspapers.com/clip/83582423/a-fine-mess/", "rt_cr_review_date": "August 17, 2021", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "Paul Attanasio", "rt_pub": "Washington Post", "rt_top": 1, "rt_cr_review": "... relies on shtick that ranges from the familiar (\"Three Stooges\"-style horseplay) to the prehistoric (as at an auction where Danson and Mandel sniff their armptis and unwittingly enter the bidding).", "rt_cr_review_full_url": "https://www.washingtonpost.com/archive/lifestyle/1986/01/18/movies/d5262bc3-07a9-4224-a0fc-36d570030eb1/?utm_term=.d68c1e8dbccd", "rt_cr_review_date": "January 3, 2018", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "Scott Weinberg", "rt_pub": "DVDTalk.com", "rt_cr_review": "Obviously inspired by the 1932 Laurel &amp; Hardy short The Music Box, A Fine Mess represents director Blake Edwards at his most witless and desperate.", "rt_cr_review_full_url": "http://dvdtalk.com/reviews/read.php?ID=19403", "rt_cr_review_date": "December 22, 2005", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "David Nusair", "rt_pub": "Reel Film Reviews", "rt_fresh": 1, "rt_cr_review": "...a thoroughly ludicrous but strangely enjoyable piece of work.", "rt_cr_review_full_url": "http://reelfilm.com/bedwards.htm#fine", "rt_cr_review_date": "November 26, 2005", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "Chuck O'Leary", "rt_pub": "Fantastica Daily", "rt_fresh": 1, "rt_cr_review_date": "September 1, 2005", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "Emanuel Levy", "rt_pub": "EmanuelLevy.Com", "rt_cr_review_date": "July 25, 2005", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "fine_mess", "rt_cr": "Walter Goodman", "rt_pub": "New York Times", "rt_top": 1, "rt_cr_review": "The acting, to use a quiet word, is broad, with everybody giving big reactions at the smallest incitement, but not broad enough to cover the lack of content.", "rt_cr_review_full_url": "http://www.nytimes.com/1986/08/08/movies/screen-edwards-s-fine-mess.html", "rt_cr_review_date": "May 21, 2003", "url": "https://www.rottentomatoes.com/m/fine_mess/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "bachelor_games", "rt_cr": "Emilie Black", "rt_pub": "Cinema Crazed", "rt_fresh": 1, "rt_cr_review": "While Bachelor Games is not the scariest film, it's well-crafted and entertaining.", "rt_cr_review_full_url": "http://cinema-crazed.com/blog/2016/07/10/bachelor-games-2016/", "rt_cr_review_date": "April 19, 2020", "url": "https://www.rottentomatoes.com/m/bachelor_games/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "bachelor_games", "rt_cr": "Naila Scargill", "rt_pub": "Exquisite Terror", "rt_fresh": 1, "rt_cr_review": "Ultimately, Bachelor Games falls flat due to lacking commitment to its ideas, but the comedy stitches it together, albeit loosely.", "rt_cr_review_full_url": "https://www.exquisiteterror.com/bachelor-games-review", "rt_cr_review_date": "February 28, 2019", "url": "https://www.rottentomatoes.com/m/bachelor_games/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "bachelor_games", "rt_cr": "Stephen Mayne", "rt_pub": "Under the Radar", "rt_cr_review": "Narrative coherency is not Bachelor Games' strength.", "rt_cr_review_full_url": "http://www.undertheradarmag.com/reviews/bachelor_games/", "rt_cr_review_date": "August 1, 2016", "url": "https://www.rottentomatoes.com/m/bachelor_games/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "bachelor_games", "rt_cr": "Scott Clark", "rt_pub": "Starburst", "rt_fresh": 1, "rt_cr_review": "When the film starts to embrace its horror side a bit more, McGown knows the audience will figure it out, so at the half-way mark turns the film on its head, revealing the true nature of the threat and the web of deceit that permitted it. It's a bold move", "rt_cr_review_full_url": "www.starburstmagazine.com", "rt_cr_review_date": "July 8, 2016", "url": "https://www.rottentomatoes.com/m/bachelor_games/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "a_story_for_the_modlins", "rt_cr": "James Wegg", "rt_pub": "JWR", "rt_fresh": 1, "rt_cr_review": "What follows is a truly magical history of the Modlins.", "rt_cr_review_full_url": "http://www.jamesweggreview.org/Articles.aspx?ID=1825", "rt_cr_review_date": "April 9, 2015", "url": "https://www.rottentomatoes.com/m/a_story_for_the_modlins/reviews", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Philip Martin", "rt_pub": "Arkansas Democrat-Gazette", "rt_cr_review": "Jersey Girl is like that new Liz Phair album ... it sometimes sounds unmistakably like Kevin Smith but you never quite believe he could be so platitudinous and predictable.", "rt_cr_review_date": "January 27, 2005", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeffrey Overstreet", "rt_pub": "Looking Closer", "rt_fresh": 1, "rt_cr_review": "Even as the critic in me raged against the clichs, I found a big old lump in my throat and blinked back a few tears.", "rt_cr_review_date": "December 31, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Mark Robison", "rt_pub": "Reno Gazette-Journal", "rt_fresh": 1, "rt_cr_review": "Kevin Smith inserts enough of his special charm to make \"Jersey Girl\" a winner.", "rt_cr_review_date": "September 9, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "\r\n                    Sunday Times (Australia)\r\n                ", "rt_cr_review_full_url": "http://www.sundaytimes.news.com.au/common/story_page/0,7034,10431612%255E14580,00.html", "rt_cr_review_date": "August 16, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Harry Haun", "rt_pub": "Film Journal International", "rt_cr_review": "This is not the hard, cutting-edge Kevin. This is the soft and runny Kevin, trying (a little too hard) to work within the system. It's lame, man.", "rt_cr_review_full_url": "http://www.filmjournal.com/filmjournal/reviews/article_display.jsp?vnu_content_id=1000695284", "rt_cr_review_date": "August 8, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jorge Avila Andrade", "rt_pub": "Moviola", "rt_fresh": 1, "rt_cr_review": "'Quiz sea reciclado de otras tantas cintas por el estilo, pero el toque de Smith aparece para hacer de este ejercicio un recomendable filme sobre el acto de maduracin.'", "rt_cr_review_date": "July 20, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Joe Utichi", "rt_pub": "FilmFocus", "rt_fresh": 1, "rt_cr_review": "It's every bit as enjoyable as [Smith's] previous attempts, but much more mature. Kevin Smith has grown up, and he's grown-up well.", "rt_cr_review_date": "July 20, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Wesley Lovell", "rt_pub": "Cinema Sight", "rt_fresh": 1, "rt_cr_review": "[on Raquel Castro] If her career is half as successful as those of similarly talented kids Christina Ricci and Kirsten Dunst, she'll be quite the sensation.", "rt_cr_review_full_url": "http://www.oscarguy.com/Reviews/Annual/2004/Jersey.html", "rt_cr_review_date": "July 11, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Christopher Smith", "rt_pub": "Bangor Daily News (Maine)", "rt_cr_review": "Kevin Smith's safest movie to date, but italso his most adult, an attempt to move beyond the comic book fantasy world in which he has lived for so long and try something new.", "rt_cr_review_full_url": "http://www.bangornews.com/editorialnews/article.cfm?ID=419947", "rt_cr_review_date": "July 8, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Matthew Turner", "rt_pub": "ViewLondon", "rt_fresh": 1, "rt_cr_review": "It's a nicely acted, competently made 'dramatic comedy' that might disappoint rabid Smith fans but is still a cut above the average Hollywood sugar-fest. Worth seeing.", "rt_cr_review_full_url": "http://www.viewlondon.co.uk/films/jersey-girl-film-review-7793.html", "rt_cr_review_date": "June 19, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Olly Richards", "rt_pub": "Empire Magazine", "rt_top": 1, "rt_cr_review": "The 'grown-up' Kevin Smith exhibits greater ambition, but he's not quite so much fun.", "rt_cr_review_full_url": "http://www.empireonline.com/reviews/ReviewComplete.asp?FID=10123", "rt_cr_review_date": "June 18, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Wendy Ide", "rt_pub": "Times (UK)", "rt_top": 1, "rt_cr_review": "The fact that Ben Affleck is required to emote should have been a warning sign to all involved with this project", "rt_cr_review_full_url": "http://www.timesonline.co.uk/article/0,,7943-1147624,00.html", "rt_cr_review_date": "June 16, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Anton Bitel", "rt_pub": "Movie Gazette", "rt_fresh": 1, "rt_cr_review": "Surprisingly unannoying...", "rt_cr_review_full_url": "http://www.movie-gazette.com/cinereviews/785", "rt_cr_review_date": "June 11, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "\r\n                    BBC.com\r\n                ", "rt_top": 1, "rt_cr_review": "Sometimes charming but frustratingly hackneyed exploration of the relationship between father and daughter.", "rt_cr_review_full_url": "http://www.bbc.co.uk/films/2004/05/21/jersey_girl_2004_review.shtml", "rt_cr_review_date": "May 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Brian Orndorf", "rt_pub": "FilmJerk.com", "rt_fresh": 1, "rt_cr_review": "A delightful dramedy that is a huge departure from the Jay and Silent Bob antics of his earlier work.", "rt_cr_review_full_url": "http://www.filmjerk.com/reviews/article.php?id_rev=284", "rt_cr_review_date": "April 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Mark Palermo", "rt_pub": "The Coast (Halifax, Nova Scotia)", "rt_cr_review": "It's Smith's embracing of romantic comedy conventions that's a letdown.", "rt_cr_review_date": "April 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Dennis Schwartz", "rt_pub": "Dennis Schwartz Movie Reviews", "rt_cr_review": "A more unbearable film than Gigli.", "rt_cr_review_full_url": "https://dennisschwartzreviews.com/jerseygirl/", "rt_cr_review_date": "April 20, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rich Cline", "rt_pub": "Shadows on the Wall", "rt_cr_review": "Retains much of Smith's astute, irreverent dialog, but once the plot kicks in, it simply stops dead in its tracks.", "rt_cr_review_full_url": "http://www.shadowsonthewall.co.uk/04/jersgirl.htm", "rt_cr_review_date": "April 18, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "James Kendrick", "rt_pub": "Q Network Film Desk", "rt_cr_review": "It feels like one of cinema's most brutally funny voices is choking on his own syrup.", "rt_cr_review_full_url": "http://www.qnetwork.com/?page=review&id=1282", "rt_cr_review_date": "April 17, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Forrest Hartman", "rt_pub": "Reno Gazette-Journal", "rt_cr_review": "The gags involve such things as Ben Affleck struggling to change a diaper. If this hadn\u2019t been done so throroughly in Three Men and a Baby, it might have been funny.", "rt_cr_review_date": "April 9, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=2", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Catharine Tunnacliffe", "rt_pub": "eye WEEKLY", "rt_cr_review": "The problem is the subject matter: a cozy ode to fatherhood with a maudlin audacity that would make Dickens blush.", "rt_cr_review_full_url": "http://www.eye.net/eye/issue/issue_03.25.04/film/onscreen.html", "rt_cr_review_date": "April 9, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Ryan Cracknell", "rt_pub": "Movie Views", "rt_fresh": 1, "rt_cr_review": "Like in all of Smith's films, the dialogue is wonderful and realistic, but also consistent with Smith's other films, there are times when the momentum doesn't hold up.", "rt_cr_review_full_url": "http://movieviews.ca/jersey-girl/", "rt_cr_review_date": "April 9, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Vince Koehler", "rt_pub": "Entertainment Spectrum", "rt_fresh": 1, "rt_cr_review": "The film weaves an intriguing story about a single dad.", "rt_cr_review_full_url": "http://www.entertainmentspectrum.com/index/movies/233.html", "rt_cr_review_date": "April 8, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Lori Hoffman", "rt_pub": "Atlantic City Weekly", "rt_fresh": 1, "rt_cr_review": "... a lightweight, but enjoyable valentine to family values and the Garden State", "rt_cr_review_date": "April 8, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "KJ Doughton", "rt_pub": "Nitrate Online", "rt_fresh": 1, "rt_cr_review": "Jersey Girl might not be Kevin Smith's most original movie, but it's daring all the same.", "rt_cr_review_full_url": "http://www.nitrateonline.com/2004/rjersey.html", "rt_cr_review_date": "April 5, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Michael Tunison", "rt_pub": "Boxoffice Magazine", "rt_cr_review": "While the mixed results aren't enough to clearly indicate whether there's a place in the world for the work of a maturing, more thoughtful Silent Bob, the film does have its strengths.", "rt_cr_review_full_url": "http://boxoffice.com/reviews/2008/08/jersey-girl.php", "rt_cr_review_date": "April 3, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Daniel M. Kimmel", "rt_pub": "Worcester Telegram &amp; Gazette", "rt_fresh": 1, "rt_cr_review": "Jersey Girl, for all its quirks, is a feel-good movie that will leave you with a smile and a lot of warm fuzzies.", "rt_cr_review_full_url": "http://64.166.24.148/datebook/moviereviews.cfm?titleid=12301&date=04/02/04&start_time=NOTPASSED&end_time=NOTPASSED", "rt_cr_review_date": "April 2, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Willie Waffle", "rt_pub": "WaffleMovies.com", "rt_fresh": 1, "rt_cr_review": "Smith is blessed with the charming Raquel Castro ... one of the best child actors I have seen in several years", "rt_cr_review_full_url": "http://www.wafflemovies.com/jerseygirl.html", "rt_cr_review_date": "April 2, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Michael Szymanski", "rt_pub": "Zap2it.com", "rt_fresh": 1, "rt_cr_review": "Smith's most family-oriented, heartfelt movie ever in his varied career. Families will love it", "rt_cr_review_full_url": "http://www.zap2it.com/movies/go?path=/movies/movies/reviews/text&general_id=21000", "rt_cr_review_date": "April 2, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Thomas Delapa", "rt_pub": "Boulder Weekly", "rt_cr_review": "The good news is that Jennifer Lopez's character dies in the first 20 minutes. The bad news is that Ben Affleck lives.", "rt_cr_review_full_url": "http://www.boulderweekly.com/screen.html", "rt_cr_review_date": "April 1, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Linda Cook", "rt_pub": "Quad City Times (Davenport, IA)", "rt_cr_review": "Kevin Smith: Come back. Your fans miss you.", "rt_cr_review_date": "March 31, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Ken Hanke", "rt_pub": "Mountain Xpress (Asheville, NC)", "rt_cr_review": "Smith has concocted a painfully predictable soap opera that would fit in very nicely on the Lifetime Network.", "rt_cr_review_full_url": "http://www.mountainx.com/movies/j/jerseygirl.php", "rt_cr_review_date": "March 31, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jonathan W. Hickman", "rt_pub": "Entertainment Insiders", "rt_cr_review": "I totally bought Carlin as a dad and grandpa, but never believed Affleck as a father.", "rt_cr_review_full_url": "http://www.einsiders.com/reviews/archives/show_theatrical.php?review_theatricle=25", "rt_cr_review_date": "March 30, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeffrey Westhoff", "rt_pub": "Northwest Herald (Crystal Lake, IL)", "rt_cr_review": "Affleck is out-acted by everyone else in the cast, including the infant who plays his daughter.", "rt_cr_review_date": "March 29, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Angela Baldassarre", "rt_pub": "Sympatico.ca", "rt_cr_review": "Kevin Smith's venture into familial territory is flat and unconvincing, despite some funny lines and interesting performances.", "rt_cr_review_date": "March 29, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Beth Jones", "rt_pub": "Roanoke Times (Virginia)", "rt_cr_review": "If the movie were any gooier, it would have been a Hallmark card.", "rt_cr_review_full_url": "http://www.roanoke.com/roatimes/news/story164784.html", "rt_cr_review_date": "March 29, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Audrey Rock-Richardson", "rt_pub": "Tooele Transcript-Bulletin (Utah)", "rt_fresh": 1, "rt_cr_review": "Anyone who's ever had a little girl will have a difficult time not liking the film.", "rt_cr_review_date": "March 29, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Mike McGranaghan", "rt_pub": "Aisle Seat", "rt_fresh": 1, "rt_cr_review": "This is not just another movie about a frustrated adult dealing with a precocious kid; it's a genuine story about a man trying to be the best dad he can be.", "rt_cr_review_full_url": "http://www.geocities.com/gamut_mag/jersgirl.htm", "rt_cr_review_date": "March 28, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rafe Telsch", "rt_pub": "CinemaBlend", "rt_fresh": 1, "rt_cr_review": "As much as Jersey Girl forces Smith to evolve both as writer and director, it also pushes Affleck.", "rt_cr_review_full_url": "http://www.filmhobbit.com/cgi-bin/movies/movies.cgi?action=showreview&review=jerseygirl", "rt_cr_review_date": "March 28, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Brian Webster", "rt_pub": "Apollo Guide", "rt_cr_review": "If there's a single authentic moment, I missed it, unless you count Ben Affleck's obnoxiousness early in the film - that part at least seems to come naturally.", "rt_cr_review_date": "March 28, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=3", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Marty Mapes", "rt_pub": "Movie Habit", "rt_fresh": 1, "rt_cr_review": "As with all of (Kevin) Smith's movies, Jersey Girl is both good and bad", "rt_cr_review_full_url": "http://www.moviehabit.com/reviews/jer_cy04.shtml", "rt_cr_review_date": "March 28, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kimberley Jones", "rt_pub": "Austin Chronicle", "rt_top": 1, "rt_cr_review": "Its heart is in the right place. Unfortunately, that heart is about the only element here that doesn't strain credibility.", "rt_cr_review_full_url": "http://www.austinchronicle.com/gyrobase/Calendar/Film?Film=oid%3a203248", "rt_cr_review_date": "March 28, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Frank Ochieng", "rt_pub": "Movie Eye", "rt_cr_review": "...barren and cloying...Ironically, Jersey Girl could use some of the disastrous Gigli-style Bennifer hype to boost this reductive romancer into moderate gear", "rt_cr_review_full_url": "http://www.movieeye.com/reviews/read_movie_review/2038.html", "rt_cr_review_date": "March 28, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Gabriel Shanks", "rt_pub": "Mixed Reviews", "rt_cr_review": "Cue the folk-rock music and close in on the tear trickling down Affleck's cheek...utter predictability.", "rt_cr_review_full_url": "http://www.tblog.com/templates/index.php?bid=mixedreviews&static=132203", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Steve Rhodes", "rt_pub": "Internet Reviews", "rt_cr_review": "Light-weight and sporadically enjoyable romantic comedy is an edge-free film by Kevin Smith's angelic twin. ... From Smith we rightly expect better.", "rt_cr_review_full_url": "http://reviews.imdb.com/Reviews/374/37436", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "J. R. Jones", "rt_pub": "Chicago Reader", "rt_top": 1, "rt_cr_review": "The grating sense of commercial calculation in Jersey Girl consistently undercuts Smith's fine writing.", "rt_cr_review_full_url": "http://www.chireader.com/movies/archives/2004/0304/040326_2.html", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "\r\n                    Baltimore Sun\r\n                ", "rt_cr_review_full_url": "http://www.sunspot.net/entertainment/movies/bal-to.jersey26mar26,0,5790553.story?coll=bal-movies-utility", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "James Verniere", "rt_pub": "Boston Herald", "rt_fresh": 1, "rt_cr_review": "Affleck moves from being the world's most famous scapegrace and goat into Hugh Grant territory, and he does it with surprising authority.", "rt_cr_review_full_url": "http://theedge.bostonherald.com/movieReviews/view.bg?articleid=86323", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Robert Wilonsky", "rt_pub": "Dallas Observer", "rt_cr_review": "Everything about the movie, from its premise of a single father raising a kid all alone to its school-musical finale, has the bland taste of reheated leftovers.", "rt_cr_review_full_url": "http://www.dallasobserver.com/issues/2004-03-25/film.html/1/index.html", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Stephanie Zacharek", "rt_pub": "Salon.com", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Inspired by Smith's own awe and amazement at being a father, the movie is modest and entertaining, with a minimum of sentimental goo, and it demands little of us except a good-natured willingness to go with it.", "rt_cr_review_full_url": "http://www.salon.com/ent/movies/review/2004/03/26/jersey_girl", "rt_cr_review_date": "March 27, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Dustin Putman", "rt_pub": "TheFilmFile.com", "rt_cr_review": "[Kevin Smith] has mistaken maturity for old Hollywood cliches and conventions.", "rt_cr_review_full_url": "http://www.themovieboy.com/directlinks/04jerseygirl.htm", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeffrey M. Anderson", "rt_pub": "Combustible Celluloid", "rt_fresh": 1, "rt_cr_review": "Smith isn't very adept at shaping or balancing the weepy scenes, but there's a sense that this material is coming, unfiltered, straight from his heart.", "rt_cr_review_full_url": "http://www.combustiblecelluloid.com/2004/jerseygirl.shtml", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Boo Allen", "rt_pub": "Denton Record-Chronicle", "rt_cr_review": "Ben Affleck is understandable. But how did Kevin Smith wind up behind something as trite and ordinary as this insipid tale?", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Michael O'Sullivan", "rt_pub": "Washington Post", "rt_top": 1, "rt_cr_review": "The filmmaker drowns his trademark edgy stew of smutty humor, stiff acting and dime-store insight into human nature with a gravy of glutinous bathos, making for a singularly unpalatable dish.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Desson Thomson", "rt_pub": "Washington Post", "rt_top": 1, "rt_cr_review": "This kind of weepy material works in the hands of melodrama masters like Douglas Sirk or Pedro Almodovar. But here, it's over-the-top and it's just horrible.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Mike Clark", "rt_pub": "USA Today", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Smith is looking more and more like a developing major talent, so it could be years until we get a handle on this movie's legacy.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Angel Cohn", "rt_pub": "TV Guide", "rt_fresh": 1, "rt_cr_review": "It's an enjoyable cruise down the Garden State Parkway, and Affleck and Castro are charming companions.", "rt_cr_review_full_url": "http://www.tvguide.com/movies/database/ShowMovie.asp?MI=45327", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Peter Howell", "rt_pub": "Toronto Star", "rt_top": 1, "rt_cr_review": "Watching Jersey Girl is akin to being smothered by a basket of warm puppies.", "rt_cr_review_full_url": "http://WWW.TheStar.COM/NASApp/cs/ContentServer?pagename=thestar/Layout/Article_Type1&c=Article&cid=1080299074451&call_pageid=1022183557980&col=1022183560753", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Moira MacDonald", "rt_pub": "Seattle Times", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "It's saved by an unusually charming child actor: Castro, who has a voice like a pan flute and a sweetly low-key screen presence.", "rt_cr_review_full_url": "http://community.seattletimes.nwsource.com/archive/?slug=jersey26&date=20040326", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Mick LaSalle", "rt_pub": "San Francisco Chronicle", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Smith is trying to say something heartfelt, even as he's using formulas that are unworthy of him. Thus, Jersey Girl is a step, not a misstep.", "rt_cr_review_full_url": "http://www.sfgate.com/cgi-bin/article.cgi?f=/c/a/2004/03/26/DDGIL5QR4R1.DTL", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=4", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "David Elliott", "rt_pub": "San Diego Union-Tribune", "rt_cr_review": "Smith, reaching into his most tender feelings, comes up with hairballs of hokum.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Joe Baltake", "rt_pub": "Sacramento Bee", "rt_fresh": 1, "rt_cr_review": "With Jersey Girl, [Smith] stopped fooling around, finally got his act together and made a real film. For once, he deserves the moniker 'filmmaker.'", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jack Garner", "rt_pub": "Rochester Democrat and Chronicle", "rt_fresh": 1, "rt_cr_review": "The point about parental responsibility is worth raising -- and Smith and company raise it with good humor and affection.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Timothy Knight", "rt_pub": "Reel.com", "rt_cr_review": "I'll take Manhattan.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Gary Thompson", "rt_pub": "Philadelphia Daily News", "rt_cr_review": "Smith never makes us believe in this story the way he clearly does.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jay Boyar", "rt_pub": "Orlando Sentinel", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Sweet and conventional, with just enough wacky Kevin Smith moments to keep it going.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "M.E. Russell", "rt_pub": "Oregonian", "rt_fresh": 1, "rt_cr_review": "Affleck, Tyler and Castro ... have a warm chemistry that melts away much of the ill will engendered by the first half-hour.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Aaron Hillis", "rt_pub": "Premiere Magazine", "rt_cr_review": "Sorry, Kevin Smith, but ditching Jay and Silent Bob doesn't mean you're all grown up yet.", "rt_cr_review_full_url": "http://www.premiere.com/article.asp?section_id=2&article_id=1522", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "John Anderson", "rt_pub": "Newsday", "rt_top": 1, "rt_cr_review": "Affleck may be a nice man, but he has a seemingly congenital inability to do anything convincingly, which is only made worse by Smith's apparent immunity to cloying sentiment.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Stephen Whitty", "rt_pub": "Newark Star-Ledger", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "This modest little date-movie may feel like a refreshing relief.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Cherryl Dawson and Leigh Ann Palone", "rt_pub": "TheMovieChicks.com", "rt_cr_review": "It almost works as a nice little film, but it's not the kind of story we want from Kevin Smith.", "rt_cr_review_full_url": "http://www.themoviechicks.com/mid2004/mcrjerseygirl.html", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Megan Lehmann", "rt_pub": "New York Post", "rt_top": 1, "rt_cr_review": "The writer-director brings nothing new to the shopworn family-vs.-work dilemma.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jack Mathews", "rt_pub": "New York Daily News", "rt_top": 1, "rt_cr_review": "Affleck is buried in the cliches of his role, or worse, having to react to the fatuousness of Tyler.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Bruce Kirkland", "rt_pub": "Jam! Movies", "rt_fresh": 1, "rt_cr_review": "Emotionally, Jersey Girl is a big ball of mush -- and I love it for Smith's willingness to be sentimental about fatherhood.", "rt_cr_review_full_url": "http://jam.canoe.ca/Movies/Reviews/J/Jersey_Girl", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Roger Ebert", "rt_pub": "Chicago Sun-Times", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "It's the kind of movie Hugh Grant might make, except for the way Smith has with his dialogue, which is truer and more direct than we expect.", "rt_cr_review_full_url": "http://www.rogerebert.com/reviews/jersey-girl-2004", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Wesley Morris", "rt_pub": "Boston Globe", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "This is a very good collection of episodes about the weekly compromises that parents make for their kids and the little dreams that children have for themselves.", "rt_cr_review_full_url": "http://www.boston.com/movies/display?display=movie&id=3302", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Spence D.", "rt_pub": "IGN Movies", "rt_fresh": 1, "rt_cr_review": "...it's a bit saccharine in places, but plenty of Smith's off-kilter sense of wit shines through, giving the rosy-cheeked script some much needed edge...", "rt_cr_review_full_url": "http://filmforce.ign.com/articles/501/501926p1.html", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kevin A. Ranson", "rt_pub": "MovieCrypt.com", "rt_fresh": 1, "rt_cr_review": "... (Kevin Smith) show(s) considerable restraint in being subtle with his subject matter... (Ben Affleck) really is leading-man material.", "rt_cr_review_full_url": "http://moviecrypt.com/CryptVault/jersey.shtml", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Sean P. Means", "rt_pub": "Salt Lake Tribune", "rt_fresh": 1, "rt_cr_review": "Jersey Girl is not Kevin Smith at his most innovative or scathingly funny. But it is his most emotionally satisfying work, a warm movie that isn't trying to be cool.", "rt_cr_review_full_url": "http://www.sltrib.com/2004/Mar/03262004/friday/151251.asp", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rebecca Murray", "rt_pub": "About.com", "rt_fresh": 1, "rt_cr_review": "I'd be lying if I didn't admit I want the other Kevin Smith back.", "rt_cr_review_full_url": "http://romanticmovies.about.com/cs/jerseygirl/a/jergirlrv032604.htm", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=5", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Austin O'Connor", "rt_pub": "Lowell Sun", "rt_cr_review": "I had trouble remembering details about Jersey Girl just an hour after it ended.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Phil Villarreal", "rt_pub": "Arizona Daily Star", "rt_cr_review": "Smith tries to stretch further in Jersey Girl, but it's all reach and no grab.", "rt_cr_review_full_url": "http://www.azstarnet.com/sn/ent_index/15437.php", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Cynthia Fuchs", "rt_pub": "PopMatters", "rt_cr_review": "The new Ben Affleck movie is less a movie than a chance for him to redeem himself for all those tabloid photos.", "rt_cr_review_full_url": "http://popmatters.com/film/reviews/j/jersey-girl.shtml", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Guylaine Cadorette", "rt_pub": "Hollywood.com", "rt_cr_review": "Director Kevin Smith tries to appeal to a more mature audience with the dramatic comedy Jersey Girl but in doing so, he loses his edge.", "rt_cr_review_full_url": "http://www.hollywood.com/review/Jersey_Girl/1746998", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Tom Meek", "rt_pub": "Boston Phoenix", "rt_fresh": 1, "rt_cr_review": "Both Smith and actor Ben Affleck get their groove back with this affecting tale of a struggling single father torn between stalled career aspirations and parental responsibility.", "rt_cr_review_full_url": "http://www.bostonphoenix.com/boston/movies/trailers/documents/03696634.asp", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Steve Schneider", "rt_pub": "Orlando Weekly", "rt_fresh": 1, "rt_cr_review": "A stone grin practically all the way through, bridging Smith's trenchcoat-mafia insouciance and soccer-dad dramatics without compromising either.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Dan Lybarger", "rt_pub": "Kansas City Star", "rt_cr_review": "Imagine Britney Spears croaking her way through La Traviata, and that's what it's like to endure Kevin Smith trying to deal with adult emotions in Jersey Girl.", "rt_cr_review_full_url": "http://www.kansascity.com/mld/kansascity/entertainment/movies/8274797.htm", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "MaryAnn Johanson", "rt_pub": "Flick Filosopher", "rt_cr_review": "Smith's first 'serious' film, is a sitcom, a mawkish, sentimental single-dad sitcom, with jokes about stinky baby poop and a cute, wiseass kid mugging for the camera.", "rt_cr_review_full_url": "http://www.flickfilosopher.com/flickfilos/archive/2004/jerseygirl.shtml", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Glenn Whipp", "rt_pub": "Los Angeles Daily News", "rt_fresh": 1, "rt_cr_review": "While the story doesn't venture far from the beaten path, Jersey Girl stands as a singular creation thanks to Smith's sharp writing and his ability to coax great performances from the most unlikely places.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Eric Harrison", "rt_pub": "Houston Chronicle", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "This is [Smith's] first mature work in which he weds his gift for quirky dialogue and humor with genuine feeling and tries to craft a story with broad appeal.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Robert Denerstein", "rt_pub": "Denver Rocky Mountain News", "rt_top": 1, "rt_cr_review": "I can understand why Smith might want to bid farewell to Jay and Silent Bob, but he needs to find something better with which to advance the cause of maturity in cinema.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeff Vice", "rt_pub": "Deseret News (Salt Lake City)", "rt_fresh": 1, "rt_cr_review": "The material here isn't exactly new but it is emotionally honest, more than a little sweet and even a bit touching. And it is by far Smith's best film.", "rt_cr_review_full_url": "http://www.deseretnews.com/article/700003490/Jersey-Girl.html", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Lisa Kennedy", "rt_pub": "Denver Post", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "A small movie with a big star doing some of his most appealing work.", "rt_cr_review_date": "March 26, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Eugene Novikov", "rt_pub": "Film Blather", "rt_fresh": 1, "rt_cr_review": "Here at last is the Kevin Smith that Chasing Amy promised.", "rt_cr_review_full_url": "http://filmblather.com/films/jerseygirl/", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "James Rocchi", "rt_pub": "Netflix", "rt_cr_review": "Potty-mouthed, pop culture-mad indie icon Kevin Smith grows up, gets serious, knuckles down ... and makes a boring movie.", "rt_cr_review_full_url": "http://www.netflix.com/MovieDisplay?movieid=60033336&trkid=23938&dmode=NETFLIXREVIEW", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rick Groen", "rt_pub": "Globe and Mail", "rt_top": 1, "rt_cr_review": "[Smith's] clerks would never have stocked it; his Amy would never have chased it; even Silent Bob might have found his voice to dump on Jersey Girl.", "rt_cr_review_full_url": "http://www.globeandmail.com/servlet/ArticleNews/movie/MOVIEREVIEWS/20040326/LADY26", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Peter Sobczynski", "rt_pub": "Critic Doctor", "rt_fresh": 1, "rt_cr_review": "'Jersey Girl' is sweet and funny and there are a few moments when Smith's snarkier side makes a welcome appearance...", "rt_cr_review_full_url": "http://www.criticdoctor.com/petersobczynski/jerseygirl.html", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "\r\n                    E! Online\r\n                ", "rt_cr_review": "A predictable and sugary been-there-before story.", "rt_cr_review_full_url": "http://www.eonline.com/Reviews/Movies/Leaves/0,20,2634,00.html", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Tom Long", "rt_pub": "Detroit News", "rt_top": 1, "rt_cr_review": "A family-positive movie that's far more interesting than most competition in the genre, but not nearly inventive enough to stand up to Smith's other work.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Sean Axmaker", "rt_pub": "Seattle Post-Intelligencer", "rt_cr_review": "His ease with characters and clever dialogue helps sustain the film through an otherwise utterly familiar story and pat, predictable ending.", "rt_cr_review_full_url": "http://seattlepi.nwsource.com/movies/166322_jersey26q.html", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=6", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeffrey Chen", "rt_pub": "ReelTalk Movie Reviews", "rt_cr_review": "One can't begrudge Smith the attempt to make a warmhearted movie about ... fatherhood, and his is a noble, heartfelt effort. More alarming, though, is how corny it turned out.", "rt_cr_review_full_url": "http://www.reeltalkreviews.com/browse/viewitem.asp?type=review&id=798", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Erik Childress", "rt_pub": "eFilmCritic.com", "rt_cr_review": "Such a generic package that it feels like just the kind of Affleck film that Smith would mock on his comic-con tours", "rt_cr_review_full_url": "http://efilmcritic.com/review.php?movie=8912&reviewer=198", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Bob Bloom", "rt_pub": "Journal and Courier (Lafayette, IN)", "rt_fresh": 1, "rt_cr_review": "Jersey Girl takes Smith in a new direction. He stumbles a bit along this new path, but shows promise and potential ...", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Bill Muller", "rt_pub": "Arizona Republic", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Jersey Girl isn't Smith's best movie, but it is his most heartfelt.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Duane Dudek", "rt_pub": "Milwaukee Journal Sentinel", "rt_cr_review": "The title is by way of Bruce Springsteen ... but the film itself has as much bite as a pop song by Paul McCartney.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "John Venable", "rt_pub": "Supercala.com", "rt_fresh": 1, "rt_cr_review": "Any romantic comedy that can work in a murdering barber can't be all bad.", "rt_cr_review_full_url": "http://www.supercalafragalistic.com/jerseygirlreview2.htm", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Josh Larsen", "rt_pub": "Sun Publications (Chicago, IL)", "rt_fresh": 1, "rt_cr_review": "Whenever `Jersey Girl' threatens to turn into `One Ben and a Baby,' Smith saves it with a good gag or clever line.", "rt_cr_review_full_url": "http://suburbanchicagonews.com/entertainment/movies/jersey.htm", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kenneth Turan", "rt_pub": "Los Angeles Times", "rt_top": 1, "rt_cr_review": "Overall too bland to hold our interest.", "rt_cr_review_full_url": "http://www.calendarlive.com/movies/reviews/cl-et-turan26mar26,2,658944.story", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Paul Salfen", "rt_pub": "Supercala.com", "rt_cr_review": "...in the same way that Smith refers to Bennifer's disaster Gigli, as 'totally watchable', this one might fall under the same backhanded classification.", "rt_cr_review_full_url": "http://www.supercalafragalistic.com/jerseygirlreview.htm", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Phoebe Flowers", "rt_pub": "South Florida Sun-Sentinel", "rt_fresh": 1, "rt_cr_review": "The Jay and Silent Bob fans may weep, but for pretty much everyone else, there's cause to rejoice.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Chris Hewitt", "rt_pub": "St. Paul Pioneer Press", "rt_cr_review": "The movie is just Baby Boom with a guy, tossed with some Jerry Maguire and bits of a zillion other movies Smith has probably trashed on his Web site.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Frederic and Mary Ann Brussat", "rt_pub": "Spirituality &amp; Practice", "rt_cr_review": "It's nice to see a screen male get lessons in being sensitive, but Ollie's emotional makeover just doesn't wash.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Harvey S. Karten", "rt_pub": "Compuserve", "rt_fresh": 1, "rt_cr_review": "Affleck's in his element.", "rt_cr_review_full_url": "http://reviews.imdb.com/Reviews/374/37419", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rene Rodriguez", "rt_pub": "Miami Herald", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "An enjoyable slice-of-life drama that offers a couple of hours spent in the company of people whose lives are recognizable from your own.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Terry Lawson", "rt_pub": "Detroit Free Press", "rt_top": 1, "rt_cr_review": "Looks like a moviemaker stretching in the wrong direction.", "rt_cr_review_full_url": "http://ae.freep.com/entertainment/ui/michigan/movie.html?id=131641&reviewId=14665", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Lawrence Toppman", "rt_pub": "Charlotte Observer", "rt_cr_review": "It's so merchandisable that I look for a direct-to-video sequel, Jersey Kidz, to hit the shelves next year.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Chris Vognar", "rt_pub": "Dallas Morning News", "rt_top": 1, "rt_cr_review": "Despite all indications that he would make a fun drinking buddy, Ben Affleck, teen idol, Oscar-winning screenwriter, can't act his way out of a paper bag.", "rt_cr_review_full_url": "http://www.guidelive.com/profile?fid=12&id=343601", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jim Lane", "rt_pub": "Sacramento News &amp; Review", "rt_fresh": 1, "rt_cr_review": "Jersey Girl does have two reasons to see it, and their names are Liv Tyler and George Carlin.", "rt_cr_review_full_url": "http://www.newsreview.com/sacramento/Content?oid=28378", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Stephen Holden", "rt_pub": "New York Times", "rt_top": 1, "rt_cr_review": "Kevin Smith has made a movie so false and blatantly icky that it's the film equivalent of making goo-goo noises and chucking a baby under the chin for 103 minutes.", "rt_cr_review_full_url": "http://www.nytimes.com/2004/03/26/movies/26JERS.html?ex=1111813200&en=1166930c7c3652f4&ei=5083&partner=Rotten Tomatoes", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Peter Travers", "rt_pub": "Rolling Stone", "rt_top": 1, "rt_cr_review": "Affleck is modest and engaging, which keeps the movie out of Gigli territory. But it's close.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=7", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Steven Rea", "rt_pub": "Philadelphia Inquirer", "rt_top": 1, "rt_cr_review": "Smith's story is like a nightmare amalgam of decades of single-dad sitcoms: mawkish, cloying, and essentially bogus.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rex Reed", "rt_pub": "Observer", "rt_top": 1, "rt_cr_review": "A mess, but forced to carry the rest of this too-saccharine but sometimes amusing film based on the personal experiences of scruffy, offbeat director Kevin Smith, Mr. Affleck has his moments.", "rt_cr_review_full_url": "http://www.nyobserver.com/pages/story.asp?ID=8817", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Laura Clifford", "rt_pub": "Reeling Reviews", "rt_fresh": 1, "rt_cr_review": "for every manipulation Smith puts us through he wins us back with offbeat heart", "rt_cr_review_full_url": "http://www.reelingreviews.com/jerseygirl.htm", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeff Strickler", "rt_pub": "Minneapolis Star Tribune", "rt_top": 1, "rt_fresh": 1, "rt_cr_review": "Although the story is fiction, the emotions are real.", "rt_cr_review_full_url": "http://www.startribune.com/stories/389/4681145.html", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Scott Foundas", "rt_pub": "L.A. Weekly", "rt_cr_review": "Festooned with bits of stale child-rearing slapstick and mawkish sentimentality, Jersey Girl is the sort of movie well-meaning movie people make when they begin to feel guilty about the level of success they've attained.", "rt_cr_review_full_url": "http://www.laweekly.com/film/film_results.php?showid=2817", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Josh Bell", "rt_pub": "Las Vegas Weekly", "rt_cr_review": "I couldn't have liked this movie any less if Affleck had stepped off the screen and punched me in the face.", "rt_cr_review_full_url": "http://www.lasvegasweekly.com/news/archive/2004/mar/25/screen_2/", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Lisa Schwarzbaum", "rt_pub": "Entertainment Weekly", "rt_top": 1, "rt_cr_review": "It's a goopy well, duh of a family drama.", "rt_cr_review_full_url": "http://www.ew.com/ew/article/0,,604200,00.html", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Nell Minow", "rt_pub": "Movie Mom", "rt_top": 1, "rt_cr_review": "Is it possible for a movie to jump the shark?", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Paul Clinton (CNN.com)", "rt_pub": "CNN.com", "rt_top": 1, "rt_cr_review": "It's way too tame for Smith's hardcore fans -- they'll probably hate every minute of it -- and not solid enough to draw new admirers.", "rt_cr_review_full_url": "http://www.cnn.com/2004/SHOWBIZ/Movies/03/25/review.jersey/index.html", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Michael Wilmington", "rt_pub": "Chicago Tribune", "rt_top": 1, "rt_cr_review": "Big, gooey (but often likable) misfire.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Nicolas Lacroix", "rt_pub": "EnPrimeur.ca", "rt_cr_review": "Le passage de Kevin Smith au cinma plus commercial et plus grand public s'avre donc un accouchement difficile.", "rt_cr_review_full_url": "http://www.enprimeur.ca/index.asp?pageID=9&reviews_id=32", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Eleanor Ringel Cater", "rt_pub": "Atlanta Journal-Constitution", "rt_top": 1, "rt_cr_review": "A treacly mess that recalls Robin Williams in his 'I need a hug' phase.", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Larry Carroll", "rt_pub": "FilmStew.com", "rt_cr_review": "The man who once envisioned a monster made entirely out of poop now only allows the substance to be used in a cutesy joke involving a baby's diaper.", "rt_cr_review_full_url": "http://www.filmstew.com/Content/ReviewsViews/Details.asp?Pg=1&ContentID=8256", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "JoBlo", "rt_pub": "JoBlo's Movie Network", "rt_fresh": 1, "rt_cr_review": "It's great to see a filmmaker you admire ... try something so completely different.", "rt_cr_review_full_url": "http://www.joblo.com/reviews.php?mode=joblo_movies&id=136", "rt_cr_review_date": "March 25, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Danny Minton", "rt_pub": "Beaumont Journal", "rt_fresh": 1, "rt_cr_review": "While sweet and stupid, it still provides for good entertainment due to its heart and wit.", "rt_cr_review_full_url": "http://www.dannyminton.com/jersey_girl.htm", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Rob Blackwelder", "rt_pub": "SPLICEDWire", "rt_cr_review": "I admire Kevin Smith for...trying to stretch (but) if this is the best he can do, please, oh please, bring back those trash-mouthed stoners Jay and Silent Bob.", "rt_cr_review_full_url": "http://splicedwire.com/04reviews/jerseygirl.html", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Tony Toscano", "rt_pub": "Talking Pictures (U.S.)", "rt_fresh": 1, "rt_cr_review": "...a warm, wonderful and touching little film.", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Sean O'Connell", "rt_pub": "Filmcritic.com", "rt_cr_review": "Smith tones down his trademark vulgarity to bring his message to the PG-13 crowd, and slices the cherished edge off his voice in the process.", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jimmy O", "rt_pub": "Film Snobs", "rt_cr_review": "Smith trades in oral sex jokes and edgy writing on relationships for the high-concept and overearnest melodrama of Jersey Girl.", "rt_cr_review_full_url": "http://www.filmsnobs.com/www/jimmyo/jerseygirl.htm", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Walter Chaw", "rt_pub": "Film Freak Central", "rt_cr_review": "A Kevin Smith movie in all its over-written, half-baked smugness, now with a thin shellac of honey-glaze.", "rt_cr_review_full_url": "http://filmfreakcentral.net/screenreviews/jerseygirl.htm", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=8", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Sean Burns", "rt_pub": "Philadelphia Weekly", "rt_cr_review": "Smith's idea of 'maturity' feels a lot like a 'very special episode' of a television sitcom. Jersey Girl is competent, gummy and bland.", "rt_cr_review_date": "March 24, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Matt Brunson", "rt_pub": "Creative Loafing", "rt_cr_review": "Where are Jay and Silent Bob when we really need them?", "rt_cr_review_full_url": "http://charlotte.creativeloafing.com/2004-03-24/film_clips.html", "rt_cr_review_date": "March 23, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Ed Park", "rt_pub": "Village Voice", "rt_top": 1, "rt_cr_review": "Has characters explain transparent motivations, to convince the gullible that the feelings here are real.", "rt_cr_review_full_url": "http://www.villagevoice.com/issues/0412/park2.php", "rt_cr_review_date": "March 23, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "James Berardinelli", "rt_pub": "ReelViews", "rt_top": 1, "rt_cr_review": "Maybe I would have been touched by this film if I had believed in the characters and their situations, but too much feels forced and scripted, the clear product of a writer's keyboard.", "rt_cr_review_full_url": "http://www.reelviews.net/movies/j/jersey_girl.html", "rt_cr_review_date": "March 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Frank Swietek", "rt_pub": "One Guy's Opinion", "rt_cr_review": "You might think you're trapped in a 'Bachelor Father' marathon...though it's hardly 'Gigli' redux, it's so mercilessly sweet and cloying that it might make you gagli.", "rt_cr_review_full_url": "http://www.oneguysopinion.com/Review.php?ID=1229", "rt_cr_review_date": "March 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jeanne Aufmuth", "rt_pub": "Palo Alto Weekly", "rt_cr_review": "Lacks the edginess and desperation that personified Kevin Smith's earlier works.", "rt_cr_review_date": "March 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Richard Roeper", "rt_pub": "Ebert &amp; Roeper", "rt_top": 1, "rt_cr_review": "Kevin Smith would have made fun of a movie like this ten years ago!", "rt_cr_review_date": "March 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kevin N. Laforest", "rt_pub": "Montreal Film Journal", "rt_cr_review": "Corny, predictable and lousily directed, but Kevin Smith still has an original voice that can be faintly heard in there somewhere.", "rt_cr_review_full_url": "http://www.montrealfilmjournal.com/review.asp?R=R0000815", "rt_cr_review_date": "March 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Scott Weinberg", "rt_pub": "eFilmCritic.com", "rt_fresh": 1, "rt_cr_review": "There's a huge streak of sincerity hidden beneath Jersey Girl's cuddly disposition. Plus it's funny.", "rt_cr_review_full_url": "http://efilmcritic.com/review.php?movie=8912&reviewer=128", "rt_cr_review_date": "March 22, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Eric Lurio", "rt_pub": "Greenwich Village Gazette", "rt_cr_review": "...too cute by half.", "rt_cr_review_date": "March 21, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Eric D. Snider", "rt_pub": "EricDSnider.com", "rt_cr_review": "So by-the-numbers, so depressingly average, that I'm tempted to believe Smith is PARODYING by-the-numbers, depressingly average films.", "rt_cr_review_full_url": "http://www.ericdsnider.com/movies/jersey-girl/", "rt_cr_review_date": "March 21, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Scott A. Mantz", "rt_pub": "Scott Mantz' Movie Reviews", "rt_fresh": 1, "rt_cr_review": "The movie rises above its cheesy contrivances to emerge as Smith's most mature (and most moving) work to date.", "rt_cr_review_full_url": "http://www.mightytreehouse.com/moviemantz/2004/03/04/jersey-girl/", "rt_cr_review_date": "March 19, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Kirk Honeycutt", "rt_pub": "Hollywood Reporter", "rt_top": 1, "rt_cr_review": "Smith stumbles setting up dramatic confrontations and strains credibility a time or two with implausible moments.", "rt_cr_review_date": "March 17, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Andrea Chase", "rt_pub": "Killer Movie Reviews", "rt_fresh": 1, "rt_cr_review": "Affleck, who often seems confused on screen . . . uses that quirk as Ollie matches wits with a kid who is not only smarter, but also probably more mature than he is", "rt_cr_review_full_url": "http://www.killermoviereviews.com/main.php?nextlink=display&dId=412", "rt_cr_review_date": "March 17, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Jon Popick", "rt_pub": "Planet S Magazine", "rt_cr_review": "Move over snowballs, stink-palms and Chinese finger-cuffs \u2013 it's time for the PG-13 Jersey Girl.", "rt_cr_review_date": "March 15, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Victoria Alexander", "rt_pub": "FilmsInReview.com", "rt_fresh": 1, "rt_cr_review": "Affleck finally scores a hit with a co-star who is nine years old.", "rt_cr_review_date": "March 11, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
{"rt_tconst": "jersey_girl", "rt_cr": "Nick Schager", "rt_pub": "Slant Magazine", "rt_top": 1, "rt_cr_review": "Kevin Smith's neuters his sense of humor for Jersey Girl, an old-fashioned ode to paternal love that shamelessly goes for its audience's tear ducts.", "rt_cr_review_full_url": "http://www.slantmagazine.com/film/review/jersey-girl", "rt_cr_review_date": "February 17, 2004", "url": "https://www.rottentomatoes.com/m/jersey_girl/reviews?type=&sort=&page=9", "spider": "rt_cr_review", "date": "20/08/2021"}
