{"mt_tconst": "two-days-one-night", "mt_director": ["Jean-Pierre Dardenne", "Luc Dardenne"], "mt_cast": ["Alain Eloy", "Batiste Sornin", "Catherine Sal\u00e9e", "Fabrizio Rongione", "Lara Persain", "Marion Cotillard", "Pili Groyne", "Simon Caudry"], "url": "https://www.metacritic.com/movie/two-days-one-night", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "national-gallery", "mt_director": ["Frederick Wiseman"], "url": "https://www.metacritic.com/movie/national-gallery", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "the-lord-of-the-rings-the-two-towers", "mt_director": ["Peter Jackson"], "mt_cast": ["Andy Serkis"], "url": "https://www.metacritic.com/movie/the-lord-of-the-rings-the-two-towers", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "point-blank-1967", "mt_director": ["John Boorman"], "mt_cast": ["Angie Dickinson", "Carroll O'Connor", "James Sikking", "John Vernon", "Keenan Wynn", "Lee Marvin", "Lloyd Bochner", "Michael Strong", "Sandra Warner", "Sharon Acker"], "url": "https://www.metacritic.com/movie/point-blank-1967", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "lincoln", "mt_director": ["Steven Spielberg"], "mt_cast": ["Daniel Day-Lewis"], "url": "https://www.metacritic.com/movie/lincoln", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "american-factory", "mt_director": ["Julia Reichert", "Steven Bognar"], "mt_cast": ["Austin Cole", "Cho Tak Wong", "Cynthia Harper", "Dave Burrows", "Jeff Daochuan Liu", "Jill Lamantia", "John Crane", "John Gauthier", "Junming 'Jimmy' Wang", "Rob Haerr", "Robert Allen", "Shawnea Rosser", "Sherrod Brown", "Wong He"], "url": "https://www.metacritic.com/movie/american-factory", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "z-1969", "mt_director": ["Costa-Gavras"], "mt_cast": ["Bernard Fresson", "Charles Denner", "Fran\u00e7ois P\u00e9rier", "Georges G\u00e9ret", "Irene Papas", "Jacques Perrin", "Jean-Louis Trintignant", "Marcel Bozzuffi", "Pierre Dux", "Yves Montand"], "url": "https://www.metacritic.com/movie/z-1969", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "behemoth", "mt_director": ["Zhao Liang"], "url": "https://www.metacritic.com/movie/behemoth", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "lenfant-the-child", "mt_director": ["Jean-Pierre Dardenne", "Luc Dardenne"], "mt_cast": ["D\u00e9borah Fran\u00e7ois", "J\u00e9r\u00e9mie Renier"], "url": "https://www.metacritic.com/movie/lenfant-the-child", "spider": "mt_director_cast", "date": "20/08/2021"}
{"mt_tconst": "the-green-knight", "mt_director": ["David Lowery"], "mt_cast": ["Alicia Vikander", "Ana\u00efs Rizzo", "Atheena Frizzell", "Barry Keoghan", "Dev Patel", "Erin Kellyman", "Helena Browne", "Joe Anderson", "Joel Edgerton", "Kate Dickie", "Nita Mishra", "Noelle Brown", "Ralph Ineson", "Sarita Choudhury", "Sean Harris", "Tara McDonagh"], "url": "https://www.metacritic.com/movie/the-green-knight", "spider": "mt_director_cast", "date": "20/08/2021"}
